version: 0.2

env:
  variables:
    MASTER_PROJECT: .\NEsper.proj
    PACKAGE_DIRECTORY: .\packages
    VERSION: 8.0.0-beta-1

phases:
  build:
    commands:
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" $env:MASTER_PROJECT'

artifacts:
  files:
    - .\build\NEsper-$env:VERSION